### PR TITLE
Fix profile.X.debug casting

### LINKED ISSUE #68: profile.XXX.debug can be u32 or bool
https://github.com/mmstick/cargo-deb/blob/4bd257dbd9700b1b587619c0938f2013e6e25e0d/src/manifest.rs#L405

Actually it can be an `u32` ([cargo code](https://github.com/rust-lang/cargo/blob/558eee4fbca56bdc4969e114ed2cc4ed7c3913bb/src/cargo/core/profiles.rs#L349))

I did not totallly understand your `fn strip_binaries()`, but I think it should be fine to cast a `0` to `false` and any other integer to `true`.

I will create a PR if this behavior suits you.

### PR DESCRIPTION
**Pull request by enizor**
As it can be an `u32`, `0` should be interpreted as false.

Since 4bd257dbd9700b1b587619c0938f2013e6e25e0d both types are parsed correctly (not included in latest release 1.10.0)

Fixes #68

### CODE REVIEW

File: src/manifest.rs [hunk 1]
```diff
@@ -402,8 +402,11 @@ impl Cargo {
             default_features: deb.default_features.unwrap_or(true),
             strip: self.profile.as_ref().and_then(|p|p.release.as_ref())
                 .and_then(|r| r.debug.as_ref())
-                .and_then(|debug| debug.as_bool())
-                .unwrap_or(true),
+                .map_or(true, |debug| match debug {
+                    toml::Value::Integer(0) => false,
+                    toml::Value::Boolean(_) => debug.as_bool().unwrap(),
```
Comment (kornelski) [inline src/manifest.rs]: Is there any reason why you don't use the value omitted by `_` here?

Comment (enizor) [reply src/manifest.rs]: No, my bad.

**Comment by kornelski** [comment]
Thanks
