### PR TITLE
fix `dpkg -i` failure caused by indented long word

### LINKED ISSUE #142: `dpkg -i` fails if readme has an indented long word
Related to #141.

If readme file has an indented long (no-spaced) word, the extended description will have an whitespace-only line, and `dpkg -i` fails.

For example, I failed to install [alacritty](https://github.com/alacritty/alacritty) due to this issue. The [README.md](https://raw.githubusercontent.com/alacritty/alacritty/master/README.md) contains these lines:

```
  <img width="600"
       alt="Alacritty running vim inside tmux"
       src="https://cloud.githubusercontent.com/assets/4285147/21585004/2ebd0288-d06c-11e6-95d3-4a2889dbbd6f.png">
```

and the last line causes the problem. `split_by_chars()` splits lines with `split(' ')`, so for example, "  indented" is split into `["", "", "indented"]`. And the last word exceeds limit, the function appends a whitespace-only line.

I wanted to fix this, but it seems not so obvious to me how to treat such cases (indentations should be kept or not?). Anyway, I post this as an issue.

### PR DESCRIPTION
**Pull request by taotao54321**
This should fix #142, and added some tests.

### CODE REVIEW

File: src/wordsplit.rs [hunk 1]
```diff
@@ -3,37 +3,60 @@ pub trait WordSplit {
...
+                // we need at least one non-whitespace character
+                if current_line.chars().all(char::is_whitespace) {
+                    append_word!(word);
+                    continue;
+                }
+
+                // now current_line has non-whitespace character
+                if current_line.len() + word.len() >= length {
+                    // if character length met or exceeded
+                    lines.push(current_line.clone());
```
Comment (kornelski) [inline src/wordsplit.rs:49]: this doesn't replace all-whitespace lines with '.'
